# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gakles <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/18 10:42:33 by gakles            #+#    #+#              #
#    Updated: 2015/09/18 11:49:58 by gakles           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = ft_display_file

SRC = ft_display_file.c

LIB = libft.a

FLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(LIB) -o $(NAME) $(SRC)

clean:

fclean:
	rm -f $(NAME)
